---
abstract: 'Creates calendars in SVG format which can be printed'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVG-Calendar
provides:
  SVG::Calendar:
    file: lib/SVG/Calendar.pm
    version: v0.2.0
requires:
  Class::Date: 0
  Clone: 0.17
  Image::ExifTool: 7.0
  Math::Trig: 1.15
  Readonly: 1.03
  SVG: 2.33
  Template: 2.14
  Template::Provider::FromDATA: 0.08
  perl: 5.008
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SVG-Calendar
  license: http://dev.perl.org/licenses/
  repository: http://github.com/ivanwills/SVG-Calendar
version: v0.2.0
